config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'note#home'
  resources :note do
     post :confirm, action: :confirm_new, on: :new
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/note_controller.rb
class NoteController < ApplicationController

  def new
    puts '***new***'
    puts 'note--'
    puts @note
    @note = Note.new
    puts 'note--'
    puts @note
  end

  def confirm_new
    puts '***confirm_new***'
    @note = Note.new(note_params)
    puts 'note--'
    puts @note
    render :new unless @note.valid?
  end

  def confirm
    puts '***confirm***'
    Note.destroy_all
    @note = Note.new(note_params)
    @note.save
    redirect_to action: 'home'
  end

  def create
    puts '***create***'
    puts 'note--'
    puts @note

    Note.destroy_all
    @note = Note.new(note_params)
    @note.save
    redirect_to action: 'home'
  end

  def home
    @notes = Note.all
  end


  private
  def note_params
    params.require(:note).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPGNote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/note/confirm.html.erb
<h1>Confirm xxx</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @note  , :url => { :controller => :note, :action => :create } do |f| %>
      <div>
        <%= f.submit "Add", class: "btn btn-primary" %>
      </div>
      <div>
        <%= simple_format f.content %>
      </div>
    <% end %>
  </div>
</div>

app/views/note/confirm_new.html.erb
<h1>Confirm  new</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if !@note.nil? %>
    <%= form_for @note  , :url => { :controller => :note, :action => :create } do |f| %>
      <div>
        <%= f.submit "Add", class: "btn btn-primary" %>
      </div>
      <div>
        <%= simple_format @note.content %>
        <%= f.hidden_field :content %>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/note/home.html.erb
<%= link_to "ADD", new_note_path , class: 'btn btn-success'%>
<div class="container">
 <table class="table table-striped">
   <thead>
   </thead>
   <tbody>
   <% if !@notes.nil? %>
   <% @notes.each do |f| %>
      <%= simple_format f.content %>
   <% end %>
   <% end %>
   </tbody>
 </table>
</div>

app/views/note/new.html.erb
<h1>Please Add</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @note , url: confirm_new_note_path do |f| %>
      <div>
        <%= f.submit "Confirm", class: "btn btn-primary" %>
      </div>
      <div>
        <%= f.text_area :content , :size => "100x800"%>
      </div>
    <% end %>
  </div>
</div>